---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 768104927725879296-a7vdLtUBfMtkIUjrPMEvsBNvfc1LH0A
:access_token_secret: Yg2zsWH6hzWotsT2TAGrjgUEghob4fjR5JOdFDDyWbnXF
